Programming/HTML_CSS_Django/Django/projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

#from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('pybo/', views.index),
    path('pybo/', include('pybo.urls')),
]

Programming/HTML_CSS_Django/Django/projects/mysite/pybo/urls.py
from django.urls import path 

from . import views #호출

urlpatterns = [
    path('pybo/', views.index),
]

Programming/HTML_CSS_Django/Django/projects/mysite/pybo/models.py
from django.db import models

# Create your models here.
#만들고자 하는 데이터베이스의 table이름이 들어오면 된다. 
class Question(models.Model): #상속에 대한 개념으로 기능을 끌어와 줘야 한다. 
    #상속했으니 부모클래스의 있는 것을 사용가능하다.
    subject = models.CharField(max_length=200) #질문 을 200길이로 제한 객체로 subject를 만들어주었다.
    #질문에 대한 부가설명 상세 
    content = models.TextField() #textfield는 글자수 제한을 두지 않음. 
    #질문이 등록된 시간
    create_date = models.DateTimeField() #날짜와 시간에 대한 기록


    def __str__(self):
        return self.subject #Question은 문자열로 찾으면 subject를 보여준다. 

#답변 테이블
class Answer(models.Model):
    #위 것과 함께 연동을 시켜줍니다.
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #외래키 가져오겠다는 지워지면 같이 지워줌
    #답변에 대한 내용
    content = models.TextField()
    create_date = models.DateTimeField()

Programming/HTML_CSS_Django/Django/projects/mysite/pybo/forms.py
from django import forms  #장고에 있는 forms라는 테이블 불러오기
from pybo.models import Question, Answer #질문을 불러오는 것이기에 Question 테이블을 불러와준다. 

class QuestionForm(forms.ModelForm): #modelForm : 입력할 수 있도록 form을 제공해준다.
    class Meta: #overriding 
        #내가 무언가 작성할 수 있는 형태로 만들어 준다.
        model = Question
        #직접 입력을 위한
        fields = ['subject', 'content']
        #수동폼을 위해
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'placeholder': "질문 상세내용 입려하세요"}),
        # }
                
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용',
        }

Programming/HTML_CSS_Django/Django/projects/mysite/pybo/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse #간단한 응답 <테스트용>

#urls.py 에 -> views.py index. 함수를 만들어야 한다. 
#리퀘스트 매개변수를 넣어줘야한다.
#요청을 받았기에 본인이 받아들이겠다는 request
def index(request):
    return HttpResponse("안녕하시오. pybo에 온 것을 환영하오.") # 전달

Programming/HTML_CSS_Django/Django/projects/mysite/templates/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        {% block test %}
        {% endblock %}
        <meta charset ="utf-8"> <!--표준 언어 규격-->
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>Hello, pybo!</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

Programming/HTML_CSS_Django/Django/projects/mysite/templates/pybo/question_detail.html
<!doctype html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        <div class="container my-3">
            <!-- 질문 -->
            <h2 class="border-bottom py-2">{{ question.subject }}</h2>
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge bg-light text-dark p-2">
                            {{ question.create_date }}
                        </div>
                    </div>
                </div>
            </div>
            <!-- 답변 -->
            <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
            {% for answer in question.answer_set.all %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge bg-light text-dark p-2">
                            {{ answer.create_date }}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- 답변 등록 -->
            <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="content" class="form-label">답변내용</label>
                    <textarea name="content" id="content" class="form-control" rows="10"></textarea>
                </div>
                <input type="submit" value="답변등록" class="btn btn-primary">
            </form>
        </div>
    </body>
</html>

Programming/HTML_CSS_Django/Django/projects/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class = "container">
    <h5 class = "my-3 border-bottom pd-2"> 질문등록 </h5>
    {% comment %} <form method ="post" action ="{% url 'pybo:question_create' %}">
        {% csrf_token %}
        {{ form.as_p }} {% endcomment %}
    <form method = "post">
        {% csrf_token %}
        <!--오류표시 start-->
        <div class ="alert alert-danger" role = "alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        <!--오류 표시 End-->
        <div class = "mb-3">
            <lable for="subject" class = "form-lable"> 제목 </label>
            <input type="text" class = "form-control" name = "subject" id = "subject" 
            value = "{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class = "mb-3">
            <lable for = "content" class = "form-lable"> 내용 </label>
            <textarea class = "form-control" name = "content" id = "content" rows = "10"> 
                {{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type = "submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

Programming/HTML_CSS_Django/Django/projects/mysite/templates/pybo/question_list.html
{% extends "base.html" %}
{% block content %}
        <style>
            a {
                color : black;
                text-decoration: none;
            }
        </style>
        <div class ="container my-3"> <!--css 클래스 여백과 관련된-->
            <table class ="table">
                <thead>
                    <tr class = "table-dark"> 
                        <th>번호</th>
                        <th>제목</th>
                        <th>작성일자</th>
                    </tr>
                </thead>
                <tbody> 
                    {% if question_list %}
                    {% for question in question_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></td>
                            <td>{{ question.create_date }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan ="3">질문이 없습니다.</td>
                        </tr>
                        {% endif %}
                    </tbody>
            </table>
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기 </a>
        </div>
{% endblock %}